### ISSUE TITLE
Developer Preview does not work for New Users

### ISSUE THREAD

**Issue by PhilippeTrounev** [LikaloLLC/docsie#8]
Looks like developer preview script does not render the developer preview for new users. Backend API seems the be returning the data.

- [ ] If you are opening and issue please include browser used, screenshot/video, necessary description and steps to reproduce the issue.
## Steps to reproduce
Register a new user
Write something do developer preview

## Expected behavior
Preview is displayed

## Actual behavior
Preview is not displayed

**Comment by PhilippeTrounev** [comment]
This has been addressed in todays build

**Comment by codesxt** [comment]
I'm still getting an issue like this. When I open the Development Preview after creating a new Shelf and Book I get the message ":( Sorry... This is not what you are looking for".

I'm also getting this message when using the live view inside one of my webpages (even if I configure the Shelf with the proper domain names).

There are two weird things that might be related:

1. The Development Preview in the example book that's created after registering in the page works fine.
2. If I open the network tab on Firefox Development Tools, it seems that the articles are being queried properly.

**Comment by PhilippeTrounev** [comment]
1. I will address the issue with new article failing publishing preview in the upcoming release. It's a bug.

2. For the second issue with rendering failing on live page, can you please share a code pen example or point me to the live page so I can take a look. You can email it to me at support@likalo.com, I am sure I can resolve it rather quickly.

**Comment by codesxt** [comment]
I just sent you a minimal html file which gives the message.

**Comment by PhilippeTrounev** [comment]
Awesome looks like the issue has been addressed. It's related to 
 https://www.docsie.io/documentation/?version=0.0.1&language=EN&article=deploying#sectionalopp
